import { Timestamp } from "firebase/firestore";

export interface BaseMetadata {
  id?: string;
  organizationId: string;
  headCoachId: string;
  athleteId: string;
  createdBy: string; // userId
  updatedBy: string; // userId
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export type AccountType = "athlete" | "head_coach" | "assistant_coach" | "support_staff" | "administrator" | "super_admin";

export interface UserBase {
  uid: string;
  email: string;
  accountType: AccountType;
  createdAt: Timestamp;
}

export interface StudentProfile {
  uid: string;
  athleteId: string; // Permanent ID (e.g., ATH-001)
  inviteCode: string; // Regeneratable code
  firstName: string;
  lastName: string;
  sport?: string;
  discipline?: string;
  category?: string;
  performanceProfile?: string;
  primaryEvent?: string;
  secondaryEvents?: string[];
  dateOfBirth?: string;
  gender?: "Men" | "Women" | "Mixed";
  ageGroup?: "U18" | "U20" | "Senior" | "Masters";
  nationality?: string;
  federationId?: string;
  passportNumber?: string;
  nationalId?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  parentGuardianName?: string;
  parentGuardianPhone?: string;
  languages?: string[];
  bloodGroup?: string;
  profilePhotoUrl?: string;
  status?: "Active" | "Injured" | "Rehabilitation" | "Off Season";
  trainingGroupId?: string;
  organizationId?: string; // Links to the current primary org
  headCoachId?: string;    // Links to current head coach
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

export interface CoachProfile {
  uid: string;
  coachId: string;
  organizationId: string;
  firstName: string;
  lastName: string;
  academyId?: string;
  profilePhotoUrl?: string;
  createdAt: Timestamp;
}

export interface StaffProfile {
  uid: string;
  staffId: string;
  inviteCode: string;
  firstName: string;
  lastName: string;
  profilePhotoUrl?: string;
  organizationId?: string;
  createdAt: Timestamp;
}

export interface Organization {
  id: string;
  name: string;
  headCoachId: string;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface TrainingGroup {
  id: string;
  organizationId: string;
  name: string;
  createdAt: Timestamp;
}

export type InviteStatus = "pending" | "accepted" | "declined";

export interface CoachInvitation {
  id: string; // Auto-generated by Firestore
  coachId: string;
  coachName: string;
  academyId: string;
  studentId: string;
  studentName: string;
  status: InviteStatus;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export interface StaffInvitation {
  id: string;
  headCoachId: string;
  headCoachName: string;
  organizationId: string;
  staffId: string;
  staffName: string;
  role: StaffRole;
  status: InviteStatus;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

export type StaffRole = "Assistant Coach" | "Sprint Coach" | "Throws Coach" | "Jump Coach" | "Strength Coach" | "Nutritionist" | "Physiotherapist" | "Sports Scientist" | "Psychologist";

export interface StaffPermissions {
  viewTraining: boolean;
  editTraining: boolean;
  viewMedical: boolean;
  editMedical: boolean;
  viewNutrition: boolean;
  editNutrition: boolean;
}

export interface StaffRelationship {
  id?: string;
  organizationId: string;
  headCoachId: string;
  staffId: string;
  athleteId?: string; // If null/undefined, applies to whole org
  trainingGroupId?: string; // If set, applies to group
  staffRole: StaffRole;
  permissions: StaffPermissions;
  status: "pending" | "active" | "suspended";
  assignedBy: string;
  assignedAt: Timestamp;
  removedAt?: Timestamp;
}

export interface CoachAthleteRelationship {
  id: string; // Format: coachId_studentId
  coachId: string; // The Head Coach
  studentId: string; // The Athlete
  createdAt: Timestamp;
  isActive: boolean;
}

export interface BodyMetric extends BaseMetadata {
  date: Timestamp;
  weight: number; // kg
  bodyFatPercentage?: number; // %
  muscleMass?: number; // kg
  restingHeartRate?: number; // bpm
  bloodPressureSys?: number;
  bloodPressureDia?: number;
  oxygenSaturation?: number; // %
  bodyTemperature?: number; // C
  boneMass?: number; // kg
  waist?: number; // cm
  chest?: number; // cm
  arm?: number; // cm
  thigh?: number; // cm
  calf?: number; // cm
  // Calculated fields (updated by service)
  bmi?: number;
  leanBodyMass?: number;
  weightChange?: number;
  bodyFatChange?: number;
  muscleChange?: number;
  notes?: string;
}

export interface WellnessLog extends BaseMetadata {
  date: Timestamp; // Beginning of day for the log
  type: "Morning" | "Evening" | "Post-Training";
  
  sleepQuality?: number; // 1-5
  sleepHours?: number;
  stressLevel?: number; // 1-5
  fatigue?: number; // 1-5
  muscleSoreness?: number; // 1-5
  hydration?: number; // 1-5
  nutrition?: number; // 1-5
  
  // Calculated fields
  readinessScore?: number; // 0-100
  complianceScore?: number; // 0-100
  riskFlags?: string[]; // e.g. ["High Fatigue", "Poor Sleep"]
  recoveryRecommendation?: string;
  todaysRecommendation?: string;
  coachAlert?: boolean;
  
  notes?: string;
}

export interface IntelligenceInsight extends BaseMetadata {
  id?: string;
  type: "warning" | "info" | "success" | "danger" | "Overtraining Risk" | "Recovery Needed";
  title: string;
  description: string;
  status: "active" | "resolved" | "dismissed";
  resolvedAt?: any;
}

export interface MedicalProfile extends BaseMetadata {
  id?: string;
  bloodGroup: string;
  allergies: string[];
  currentMedications: string[];
  chronicConditions: string[];
  previousSurgeries: { procedure: string; date: string; }[];
  vaccinations: string[];
  emergencyContacts: any[];
  insuranceInfo: string;
  lastPhysical: string;
}

export interface Notification extends BaseMetadata {
  id?: string;
  recipientId: string;
  title: string;
  message: string;
  type: string;
  isRead: boolean;
  actionUrl?: string;
}

export interface CalendarEvent extends BaseMetadata {
  id?: string;
  title: string;
  description: string;
  start: any;
  end: any;
  location?: string;
  attendees: string[];
  type: "training" | "competition" | "medical" | "meeting" | "other";
}

export interface Subscription extends BaseMetadata {
  id?: string;
  organizationId: string;
  planId: string;
  status: "active" | "past_due" | "canceled" | "unpaid" | "trialing";
  currentPeriodStart: Timestamp;
  currentPeriodEnd: Timestamp;
  cancelAtPeriodEnd: boolean;
  stripeSubscriptionId?: string;
  stripeCustomerId?: string;
}

export interface Payment extends BaseMetadata {
  id?: string;
  organizationId: string;
  amount: number;
  currency: string;
  status: "succeeded" | "pending" | "failed" | "refunded";
  paymentMethod: string;
  gateway: string;
  transactionId: string;
  date: Timestamp;
  invoiceUrl?: string;
}

export interface Plan {
  id: string;
  name: string;
  monthlyPrice: number;
  annualPrice: number;
  athleteLimit: number;
  coachLimit: number;
  storageLimitGB: number;
  features: string[];
  trialDays: number;
  isActive: boolean;
}

export interface Coupon {
  id?: string;
  code: string;
  description: string;
  discountPercentage?: number;
  flatDiscount?: number;
  maxDiscount?: number;
  minPurchase?: number;
  usageLimit?: number;
  usagePerUser?: number;
  timesUsed: number;
  startDate: Timestamp;
  expiryDate: Timestamp;
  status: "active" | "inactive" | "expired";
  revenueGenerated: number;
}

export interface Announcement extends BaseMetadata {
  id?: string;
  title: string;
  content: string;
  type: "banner" | "popup" | "email" | "notification";
  target: "global" | "organizations" | "coaches";
  targetIds?: string[];
  startDate: Timestamp;
  endDate?: Timestamp;
  isActive: boolean;
}

export interface SupportTicket extends BaseMetadata {
  id?: string;
  subject: string;
  description: string;
  status: "open" | "in_progress" | "resolved" | "closed";
  priority: "low" | "medium" | "high" | "critical";
  userId: string;
  assigneeId?: string;
  attachments?: string[];
  replies: {
    id: string;
    userId: string;
    content: string;
    createdAt: Timestamp;
    isAdmin: boolean;
  }[];
}

export interface FeatureFlag {
  id: string;
  name: string;
  description: string;
  isEnabled: boolean;
  updatedAt: Timestamp;
  updatedBy: string;
}

export interface AuditLog {
  id?: string;
  timestamp: Timestamp;
  adminId: string;
  adminEmail: string;
  action: string;
  targetId: string;
  targetType: string;
  ipAddress?: string;
  result: "success" | "failure";
  details?: any;
}

export interface SystemSettings {
  id: string;
  platformName: string;
  platformLogoUrl: string;
  supportEmail: string;
  maintenanceMode: boolean;
  privacyPolicyUrl: string;
  termsUrl: string;
  refundPolicyUrl: string;
  gstPercentage: number;
  defaultCurrency: string;
  timezone: string;
  brandPrimaryColor: string;
  brandSecondaryColor: string;
}

export interface CompetitionSnapshot extends Omit<BaseMetadata, "athleteId"> {
  id?: string;
  name: string;
  date: Timestamp;
  venue: string;
  season: string;
  isIndoor: boolean;
  status: "upcoming" | "in_progress" | "completed" | "archived";
  athletes: string[]; // List of athleteIds participating
  results: {
    athleteId: string;
    eventId: string;
    performance: number | string; 
    wind?: number;
    points?: number;
    rank?: number;
    notes?: string;
  }[];
  isOfficial: boolean; // Differentiates from casual training meets
}

export interface PerformanceTimelineLog extends BaseMetadata {
  id?: string;
  eventId: string;
  performanceValue: number; // Base unit (e.g., ms for time, mm for distance) for math
  formattedPerformance: string; // e.g., "10.39s", "6.85m"
  date: Timestamp;
  context: "training" | "competition" | "target";
  dataSource: "manual_coach" | "manual_athlete" | "competition_result" | "csv_import" | "wearable" | "timing_system" | "gps" | "force_plate";
  competitionId?: string; // Link to CompetitionSnapshot if applicable
  venue?: string;
  weather?: string;
  wind?: number;
  season: string;
  waPoints?: number; // World Athletics points if applicable
  isPB?: boolean;
  isSB?: boolean;
}

export interface SystemAuditLog extends BaseMetadata {
  id?: string;
  actorId: string; // The user who performed the action
  actorRole: string; // Their role at the time
  action: string; // e.g., "CHANGED_CATEGORY", "UPDATED_TARGET"
  targetId: string; // The entity changed
  targetType: "athlete" | "competition" | "performance" | "kpi" | "organization";
  details: any; // JSON object representing the change (before/after)
  ipAddress?: string;
}


